config/urls.py
from allauth.account.views import PasswordChangeView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


class CustomPasswordChangeView(PasswordChangeView):
    success_url = "/"


urlpatterns = [
    path(settings.ADMIN_PATH + "/", admin.site.urls),
    path("", include("penzoe.core.urls")),
    path("words/", include("penzoe.words.urls", namespace="words")),
    path("quiz/", include("penzoe.quiz.urls", namespace="quiz")),
    path("users/", include("penzoe.users.urls", namespace="users")),
    path("discourse/", include("penzoe.discourse.urls", namespace="discourse")),
    path(
        "accounts/password/change/",
        CustomPasswordChangeView.as_view(),
        name="account_password_change",
    ),
    path("accounts/", include("allauth.urls")),
    path("api/", include("config.api_router")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    if settings.DEBUG_TOOLBAR:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

penzoe/core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [path("", views.IndexView.as_view(), name="index")]

penzoe/quiz/urls.py
from django.urls import path

from .views import get_spelling_mcq

app_name = "quiz"
urlpatterns = [
    path("spelling-mcq/<str:level>/", view=get_spelling_mcq, name="spelling-mcq")
]

penzoe/users/urls.py
from django.urls import path

from .views import profile

app_name = "users"
urlpatterns = [path("profile/", profile, name="profile")]

penzoe/words/urls.py
from django.urls import path

from .views import word_detail_view, word_list_view

app_name = "words"
urlpatterns = [
    path("", view=word_list_view, name="list"),
    path("<int:pk>/", view=word_detail_view, name="detail"),
]

templates/base.html
{% load static %}
<!docktype html>
<html lang="en">
  <head>
    <!-- Require meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous"
    />

    <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

    <title>{% block head_title %}{% endblock %} &ndash Penzoe</title>
  </head>

  <body class="d-flex flex-column h-100">
    {% block navigation %}
      {% include "nav.html" %}
    {% endblock %}

    <main class="container">
      {% if messages %}
        {% for message in messages %}
          <div class="mt-2 alert alert-{{ message.tags }}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block main %} {% endblock %}
    </main>

    <footer class="footer mt-auto py-3 bg-light">
      <div class="container text-center">
        <span class="text-muted">
          &copy 2021 - Penzoe
        </span>
      </div>
    </footer>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-auto">
  <div class="container">
    <a class="navbar-brand" href="{% url 'core:index' %}">Penzoe</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2">
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Quiz
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'quiz:spelling-mcq' 'C1' %}">Spelling</a></li>
            <li>
              <a class="dropdown-item" href="vocabulary-test">Vocabulary</a>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'words:list' %}">Words</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="vocabulary-test">Grammar</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="idioms">Idioms</a>
        </li>
      </ul>
      {% if not request.user.is_authenticated %}
      <a class="p-2 text-light" href="/accounts/login/">Log In</a>
      <a class="btn btn-primary" href="/accounts/signup/">Sign Up</a>
      {% else %}
      <a class="p-3 link-info" href="{% url 'users:profile' %}"
        >{{ request.user.username }}</a
      >
      <a class="p-2 text-light" href="/accounts/logout/">Logout</a>
      {% endif %}
    </div>
  </div>
</nav>